# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'HelloWorld_KMM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'hello_world', :path => './../AndroidStudioProjects/HelloWorld/hello_world'
  pod 'KMPNativeCoroutinesAsync', '0.12.5'
  
end
